quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: none

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Objective API
          version: 0.0.1
          description: API for retrieving Objectives
          contact:
            email: techsupport@redhat.com
            name: Customer API Support
            url: https://github.com/MundakaZgz/okr-services/customer-api
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html